### ISSUE TITLE
Include python docstring support

### ISSUE THREAD

**Issue by paulosmolski** [glts/vim-textobj-comment#8]
Hi, I'd like to say that I really like your plugin. However I've noticed that it doesn't have a proper python support - it doesn't detect python docstrings as comments. Could you please add this functionality?

**Comment by glts** [comment]
This plugin uses Vim’s `comments` and `commentstring` settings to recognise comments. In Python, only `#` is supported as a comment character.

```
:set commentstring?
  commentstring=# %s
```

I don’t want to add additional code for recognising strings, and so – unfortunately for you – have to close this issue.
